from html import escape
import pytest
from utils.api_client import APIClient, config as api_config


def _load_settings():
    return dict(api_config)


def _dashboard_settings():
    dashboard = api_config.get("dashboard") or {}
    if not isinstance(dashboard, dict):
        dashboard = {}
    title = str(dashboard.get("title") or "API QA Test Suite")
    subtitle = str(dashboard.get("subtitle") or "Automated quality report")
    brand_text = str(dashboard.get("brand_text") or "QA")[:4]
    return {
        "title": title,
        "subtitle": subtitle,
        "brand_text": brand_text,
    }


def _report_title():
    title = _dashboard_settings()["title"]
    if "dashboard" in title.lower():
        return title
    return f"{title} Dashboard"


def _format_nodeid(report):
    nodeid = report.nodeid.replace("\\", "/")
    parts = nodeid.split("::")
    source = parts[0].replace("tests/", "")
    scenario = parts[-1] if len(parts) > 1 else source
    if report.when != "call":
        scenario = f"{scenario} ({report.when})"
    return source, scenario

@pytest.fixture(scope="session")
def settings():
    """Load config once per session."""
    return _load_settings()

@pytest.fixture(scope="session")
def api(settings):
    """Reusable API client for all tests."""
    return APIClient(base_url=settings["base_url"], token=settings.get("auth_token", ""))


def pytest_html_report_title(report):
    report.title = _report_title()


def pytest_html_results_summary(prefix, summary, postfix, session):
    settings = dict(api_config)
    dashboard = _dashboard_settings()
    extra_headers = settings.get("extra_headers") or {}
    api_key = extra_headers.get("x-api-key")
    mode = "Live endpoint checks" if api_key else "Preview mode (no API key)"
    target = escape(settings.get("base_url", "Not configured"))
    scenario_count = len(session.items)
    scenario_label = "scenario" if scenario_count == 1 else "scenarios"
    title = escape(dashboard["title"])
    subtitle = escape(dashboard["subtitle"])
    brand_text = escape(dashboard["brand_text"])

    prefix.extend(
        [
            (
                '<section class="qa-brand">'
                f'<div class="qa-brand__mark">{brand_text}</div>'
                '<div class="qa-brand__content">'
                f'<p class="qa-brand__title">{title}</p>'
                f'<p class="qa-brand__subtitle">{subtitle}</p>'
                "</div>"
                "</section>"
                '<section class="qa-hero">'
                '<p class="qa-hero__eyebrow">Release Readiness Snapshot</p>'
                '<div class="qa-hero__grid">'
                f'<div class="qa-metric"><span class="qa-metric__label">Target</span><strong>{target}</strong></div>'
                f'<div class="qa-metric"><span class="qa-metric__label">Suite</span><strong>{scenario_count} {scenario_label}</strong></div>'
                f'<div class="qa-metric"><span class="qa-metric__label">Mode</span><strong>{escape(mode)}</strong></div>'
                "</div>"
                "</section>"
            )
        ]
    )
    summary.append(
        (
            '<p class="qa-summary-note">'
            "This dashboard is generated by GitHub Actions and published through GitHub Pages."
            "</p>"
        )
    )
    if not api_key:
        postfix.append(
            (
                '<p class="qa-summary-note qa-summary-note--warning">'
                "Add <code>extra_headers.x-api-key</code> in config/settings.json or a "
                "<code>REQRES_API_KEY</code> GitHub Actions secret to run the live ReqRes smoke check."
                "</p>"
            )
        )


def pytest_html_results_table_header(cells):
    cells[0] = '<th class="sortable" data-column-type="result">Status</th>'
    cells[1] = '<th class="sortable" data-column-type="testId">Scenario</th>'
    cells[2] = '<th class="sortable" data-column-type="duration">Runtime</th>'
    cells[3] = "<th>Artifacts</th>"


def pytest_html_results_table_row(report, cells):
    source, scenario = _format_nodeid(report)
    cells[1] = (
        '<td class="col-testId">'
        f'<span class="qa-test-name">{escape(scenario)}</span>'
        f'<span class="qa-test-path">{escape(source)}</span>'
        "</td>"
    )
